import { LegalLayout } from "./LegalLayout";
import { H2, P, Ul } from "./shared";

export function Disclaimer() {
  return (
    <LegalLayout title="AI & Recipe Disclaimer" lastUpdated="September 1, 2026">
      <P>
        Recipes and recipe ideas provided by What Should I Cook are generated by AI and have not
        been individually tested or reviewed by a chef, nutritionist, or food-safety professional.
      </P>

      <H2>AI-generated recipes may contain mistakes</H2>
      <P>
        AI-generated recipes can contain incorrect ingredients, quantities, cooking times,
        temperatures, or instructions. Treat the results as ideas rather than verified recipes.
      </P>

      <H2>Always check before cooking</H2>
      <P>Before preparing or serving a recipe, use your own judgment and verify:</P>
      <Ul>
        <li>Ingredients and quantities</li>
        <li>Cooking times and temperatures</li>
        <li>Food-safety requirements</li>
        <li>Allergens and potential cross-contamination</li>
        <li>Dietary requirements or restrictions</li>
      </Ul>

      <H2>Allergies and dietary preferences</H2>
      <P>
        Allergy and dietary options in the Service are provided to help guide the AI, but they do
        not guarantee that a recipe is free from a particular allergen or suitable for a specific
        diet.
      </P>
      <P>
        If you or someone you are cooking for has a serious or life-threatening allergy, do not
        rely on an AI-generated recipe as a safety measure. Always check ingredients and product
        labels carefully.
      </P>

      <H2>Not professional advice</H2>
      <P>The Service does not provide medical, nutritional, or professional food-safety advice.</P>
      <P>
        If you have a medical condition, serious allergy, or specific dietary requirement that
        requires professional guidance, consult an appropriate qualified professional.
      </P>
      <P>
        By using the Service, you acknowledge that you are responsible for verifying and deciding
        whether a recipe is appropriate and safe for you and anyone you serve it to.
      </P>
      <P>
        See our{" "}
        <a href="/terms" className="text-accent-hover underline underline-offset-2">
          Terms of Use
        </a>{" "}
        for additional information.
      </P>
    </LegalLayout>
  );
}
