import { LegalLayout } from "./LegalLayout";
import { H2, P, Ul } from "./shared";

export function Disclaimer() {
  return (
    <LegalLayout title="AI & Recipe Disclaimer" lastUpdated="August 31, 2026">
      <P>
        Every recipe idea, ingredient list, quantity, and cooking instruction shown by this
        Service is generated automatically by an AI language model — not written, tested, or
        reviewed by a chef, nutritionist, food safety expert, or any human at all. Please read
        this before you cook.
      </P>

      <H2>AI-generated content can be wrong</H2>
      <P>
        Large language models generate plausible-sounding text based on patterns, not verified
        culinary knowledge. A recipe can look complete and confident while still containing
        mistakes: an ingredient that doesn't belong, a quantity that's off, a missing step, an
        unsafe cooking temperature or time, or a combination that doesn't actually work in
        practice. Treat every result as a starting idea, not a tested, reliable recipe.
      </P>

      <H2>You must independently verify, every time</H2>
      <P>Before you shop, cook, or serve anything based on a suggestion from this Service, independently check:</P>
      <Ul>
        <li><strong className="text-text">Ingredients</strong> — that they're correct, safe, and actually appropriate for the dish.</li>
        <li><strong className="text-text">Quantities</strong> — that measurements and proportions make sense.</li>
        <li><strong className="text-text">Cooking instructions</strong> — that temperatures, times, and techniques (especially for meat, poultry, seafood, and eggs) meet safe food-handling standards.</li>
        <li><strong className="text-text">Allergens</strong> — that nothing in the recipe conflicts with your or your guests' allergies or intolerances, even if you selected an allergy filter in the app (see below).</li>
        <li><strong className="text-text">Dietary suitability</strong> — that the recipe actually fits any dietary requirement, medical condition, or religious/ethical restriction you're relying on it for.</li>
      </Ul>

      <H2>Allergy and dietary filters are a preference, not a guarantee</H2>
      <P>
        This Service lets you flag allergies and dietary needs so the AI can try to avoid
        conflicting ingredients. This is a best-effort instruction to the AI model, not a
        verified, guaranteed exclusion. The model can still make mistakes, including missing
        derivative or hidden sources of an allergen. If an allergy is serious or life-threatening,
        do not rely on this Service, or any AI tool, as your safeguard — always verify every
        ingredient yourself.
      </P>

      <H2>No professional advice</H2>
      <P>
        Nothing generated by this Service constitutes professional culinary, nutritional, or
        medical advice. If you have specific health conditions, allergies, or dietary needs that
        require professional guidance, consult a qualified doctor, dietitian, or other
        professional rather than relying on AI-generated suggestions.
      </P>

      <H2>Use at your own judgment</H2>
      <P>
        By using this Service, you acknowledge that you are relying on your own judgment — not
        ours or the AI model's — for every decision about what to cook, buy, and eat. See our{" "}
        <a href="#/terms" className="text-accent-hover underline underline-offset-2">
          Terms of Use
        </a>{" "}
        for how this applies legally.
      </P>
    </LegalLayout>
  );
}
