import { LegalLayout } from "./LegalLayout";
import { H2, P, Ph, Ul } from "./shared";

export function TermsOfUse() {
  return (
    <LegalLayout title="Terms of Use" lastUpdated="August 31, 2026">
      <P>
        These Terms of Use ("Terms") govern your use of "What Should I Cook" (the "Service"), an
        anonymous, AI-powered recipe idea generator. By using the Service, you agree to these
        Terms. If you don't agree, please don't use the Service.
      </P>

      <H2>What this Service is</H2>
      <P>
        The Service lets you submit ingredients or a food-related request and receive
        AI-generated recipe ideas. No account is required, and none is offered. There is no
        guarantee of accuracy, availability, or fitness for any particular purpose — see the{" "}
        <a href="#/disclaimer" className="text-accent-hover underline underline-offset-2">
          AI &amp; Recipe Disclaimer
        </a>{" "}
        for details specific to the recipe content itself.
      </P>

      <H2>Acceptable use</H2>
      <P>You agree to use the Service only for its intended purpose: getting recipe ideas. In particular, you agree not to:</P>
      <Ul>
        <li>Use the Service for any unlawful purpose, or to generate content intended to harm, harass, or deceive others.</li>
        <li>Attempt to extract, reproduce, or resell the Service's output at scale, or otherwise use it as a substitute for direct access to the underlying AI provider.</li>
        <li>Interfere with, disrupt, or place undue load on the Service or the infrastructure it runs on.</li>
        <li>Reverse-engineer, scrape, or build automated tooling around the Service beyond normal, individual, human use.</li>
      </Ul>

      <H2>Abuse, automated requests, and rate limits</H2>
      <P>
        Because the Service is free and open to anyone without an account, we apply technical
        protections — including rate limiting, request-size limits, and automated abuse
        detection — to keep it available and to control costs. You agree not to attempt to bypass,
        circumvent, disable, or interfere with these protections, including by using scripts, bots,
        or other automated means to send requests faster or in greater volume than a normal human
        user would, or by attempting to manipulate request parameters to obtain behavior the
        Service does not intentionally offer.
      </P>
      <P>
        We may block, throttle, or otherwise restrict access (temporarily or permanently) for any
        traffic we reasonably believe is abusive, automated in a way that harms the Service, or in
        violation of these Terms, without prior notice.
      </P>

      <H2>Service availability</H2>
      <P>
        The Service is provided on an "as available" basis. We do not guarantee uninterrupted or
        error-free operation, and features (including AI generation itself) may be temporarily
        disabled, rate-limited, or modified — including to protect the Service from cost overruns
        or abuse — without prior notice.
      </P>

      <H2>AI-generated content and accuracy</H2>
      <P>
        Recipe titles, descriptions, ingredient lists, and instructions are generated by a
        third-party AI model and are not reviewed by a human before being shown to you. AI-generated
        content can be inaccurate, incomplete, nonsensical, or unsafe if followed literally. You
        are solely responsible for evaluating and verifying any content before relying on it —
        see the{" "}
        <a href="#/disclaimer" className="text-accent-hover underline underline-offset-2">
          AI &amp; Recipe Disclaimer
        </a>{" "}
        for specifics on food safety and allergens.
      </P>

      <H2>Your responsibility</H2>
      <P>
        You are responsible for what you type into the Service and for any decisions you make
        based on its output — including what you cook, eat, serve to others, or purchase. This
        includes verifying ingredient safety, checking for allergens, confirming cooking
        temperatures and times are safe, and using your own judgment, especially for anyone with
        food allergies, medical dietary restrictions, or other health-sensitive needs.
      </P>

      <H2>Intellectual property</H2>
      <P>
        The Service's design, branding, logo, and underlying source code are owned by{" "}
        <Ph>your name or business name</Ph> unless otherwise noted, and may not be copied or
        reused without permission. AI-generated recipe text is provided to you for personal,
        non-commercial use. Because it is machine-generated, such content may not carry the same
        copyright protections as human-authored work in every jurisdiction, and similar or
        identical suggestions may be generated for other users from similar inputs.
      </P>

      <H2>Prohibited misuse</H2>
      <P>In addition to the acceptable-use rules above, you may not use the Service to:</P>
      <Ul>
        <li>Attempt to extract our system prompts, API keys, provider configuration, or other backend implementation details.</li>
        <li>Submit content designed to manipulate the AI model into producing harmful, illegal, or policy-violating output unrelated to recipes.</li>
        <li>Probe, scan, or test the Service's security, rate limiting, or infrastructure without prior written permission.</li>
      </Ul>

      <H2>Limitation of liability</H2>
      <P>
        To the maximum extent permitted by applicable law, the Service is provided "as is" and "as
        available," without warranties of any kind, express or implied. We are not liable for any
        harm, loss, illness, injury, or damages arising from your use of the Service or reliance on
        its output, including but not limited to issues arising from AI-generated recipe content,
        food safety, or allergic reactions. Nothing in these Terms limits liability that cannot be
        limited under the law of <Ph>governing jurisdiction</Ph>.
      </P>

      <H2>Changes and discontinuation</H2>
      <P>
        We may update these Terms, modify or discontinue the Service (or any part of it, including
        AI generation itself), at any time, with or without notice. Continued use of the Service
        after changes are posted constitutes acceptance of the updated Terms. The "Last updated"
        date above reflects the current version.
      </P>

      <H2>Governing law</H2>
      <P>
        These Terms are governed by the laws of <Ph>governing jurisdiction — to be confirmed</Ph>,
        without regard to conflict-of-law principles, except where applicable local law provides
        otherwise.
      </P>

      <H2>Contact</H2>
      <P>
        Questions about these Terms can be sent via the{" "}
        <a href="#/contact" className="text-accent-hover underline underline-offset-2">
          Contact page
        </a>
        .
      </P>
    </LegalLayout>
  );
}
