import { LegalLayout } from "./LegalLayout";
import { H2, P, Ul } from "./shared";

export function TermsOfUse() {
  return (
    <LegalLayout title="Terms of Use" lastUpdated="September 1, 2026">
      <P>
        These Terms of Use govern your use of What Should I Cook, an AI-powered recipe idea
        generator. By using the Service, you agree to these Terms. If you do not agree, please do
        not use the Service.
      </P>

      <H2>Using the Service</H2>
      <P>
        What Should I Cook allows you to enter ingredients, preferences, or other food-related
        requests and receive AI-generated recipe ideas.
      </P>
      <P>The Service is provided for general informational and entertainment purposes. No account is required to use it.</P>

      <H2>Acceptable Use</H2>
      <P>You agree to use the Service responsibly and only for lawful purposes.</P>
      <P>You must not:</P>
      <Ul>
        <li>Abuse, overload, disrupt, or interfere with the Service.</li>
        <li>Use bots, scripts, or other automated systems to send excessive requests.</li>
        <li>Attempt to bypass rate limits or other security measures.</li>
        <li>Scrape, copy, or reproduce the Service at scale.</li>
        <li>Attempt to access unauthorized parts of the Service or its underlying systems.</li>
        <li>Attempt to obtain API keys, credentials, system instructions, or other confidential information.</li>
      </Ul>
      <P>
        We may temporarily or permanently restrict access if we reasonably believe the Service is
        being abused or these Terms are being violated.
      </P>

      <H2>AI-Generated Recipes</H2>
      <P>
        Recipe ideas, ingredients, quantities, cooking instructions, and other content generated
        by the Service are produced by an AI system and are not individually reviewed by a human.
      </P>
      <P>AI-generated content may contain mistakes, omissions, or inaccurate information.</P>
      <P>
        You should independently verify recipe information before using it. For important
        information about food safety, allergens, and dietary restrictions, please see our{" "}
        <a href="/disclaimer" className="text-accent-hover underline underline-offset-2">
          AI &amp; Recipe Disclaimer
        </a>
        .
      </P>

      <H2>Your Responsibility</H2>
      <P>You are responsible for how you use the information provided by the Service.</P>
      <P>
        Always use your own judgment and verify ingredients, allergens, cooking temperatures,
        cooking times, and food-safety information before preparing or serving food.
      </P>
      <P>Do not rely on AI-generated recipes as medical or nutritional advice.</P>

      <H2>Intellectual Property</H2>
      <P>
        The Service's name, branding, design, logo, and underlying software are protected by
        applicable intellectual-property laws and may not be copied or reused without permission.
      </P>
      <P>Recipe ideas generated by the Service are AI-generated and may be similar to ideas generated for other users.</P>

      <H2>Availability</H2>
      <P>We aim to keep the Service available and reliable, but we do not guarantee that it will always be available, uninterrupted, or error-free.</P>
      <P>We may modify, suspend, or discontinue the Service or its features, including AI generation, at any time.</P>

      <H2>Disclaimer and Limitation of Liability</H2>
      <P>The Service and its AI-generated content are provided on an "as is" and "as available" basis.</P>
      <P>
        To the maximum extent permitted by applicable law, we make no guarantees regarding the
        accuracy, completeness, reliability, or suitability of AI-generated recipe content.
      </P>
      <P>
        To the extent permitted by law, we are not responsible for losses, damages, illness,
        injury, allergic reactions, or other consequences resulting from reliance on or use of
        information provided by the Service.
      </P>
      <P>Nothing in these Terms excludes or limits liability that cannot legally be excluded or limited.</P>

      <H2>Changes to These Terms</H2>
      <P>
        We may update these Terms when the Service or its practices change. The updated version
        will be posted on this page with a new "Last updated" date.
      </P>
      <P>Your continued use of the Service after changes are posted means you accept the updated Terms.</P>

      <H2>Contact</H2>
      <P>
        If you have questions about these Terms, please contact us through the{" "}
        <a href="/contact" className="text-accent-hover underline underline-offset-2">
          Contact page
        </a>
        .
      </P>
    </LegalLayout>
  );
}
