name = "what-should-i-cook-api"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[observability]
enabled = true

[[durable_objects.bindings]]
name = "RATE_LIMITER_DO"
class_name = "RateLimiterDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RateLimiterDO"]
